### ISSUE TITLE
Does not work with ng 15

### ISSUE THREAD

**Issue by mcwebdev** [plotly/angular-plotly.js#228]
I am getting an error with simple github example with ng15.
Error: Invalid PlotlyJS object. Please check https://github.com/plotly/angular-plotly.js#quick-start to see how to add PlotlyJS to your project.
    at new PlotlyModule (angular-plotly.js.js:532:19) [angular]
    at Object.PlotlyModule_Factory [as useFactory] (angular-plotly.js.js:541:63) [angular]
    at Object.factory (core.mjs:8155:38) [angular]
    at R3Injector.hydrate (core.mjs:8068:35) [angular]
    at R3Injector.get (core.mjs:7956:33) [angular]
    at injectInjectorOnly (core.mjs:633:33) [angular]
    at ɵɵinject (core.mjs:637:60) [angular]
    at useValue (core.mjs:7750:65) [angular]
    at R3Injector.resolveInjectorInitializers (core.mjs:8005:17) [angular]
    at new NgModuleRef (core.mjs:19838:26) [angular]
    at NgModuleFactory.create (core.mjs:19862:16) [angular]
    at :4200/vendor.js:507709:39 [angular]
    at Object.onInvoke (core.mjs:24238:33) [angular]

**Comment by mcwebdev** [comment]
dont forget to add import { CommonModule } from '@angular/common';
