### ISSUE TITLE
Jest Tests: Error:  TypeError: window.URL.createObjectURL is not a function

### ISSUE THREAD

**Issue by jeckgit** [plotly/angular-plotly.js#88]
-----------------------------
Node: 12.13.1
OS: linux x64
Angular: 8.1.2
jest:  24.9.0
-----------------------------
If I run the following test in jest, to check if the app module Instance can get created:
```
describe('AppModule', () => {
  let appModule: AppModule;

  beforeEach(() => {
    appModule = new AppModule();
  });

  it('should create an instance', () => {
    expect(appModule).toBeTruthy();
  });
});
```
I get the following Error:
```
Test suite failed to run

    TypeError: window.URL.createObjectURL is not a function



      at define (../../../node_modules/mapbox-gl/dist/mapbox-gl.js:24:37)
      at ../../../node_modules/mapbox-gl/dist/mapbox-gl.js:33:1
      at ../../../node_modules/mapbox-gl/dist/mapbox-gl.js:3:81
      at Object.<anonymous> (../../../node_modules/mapbox-gl/dist/mapbox-gl.js:6:2)
      at Object.<anonymous> (../../../node_modules/plotly.js/src/plots/mapbox/index.js:11:16)
      at Object.<anonymous> (../../../node_modules/plotly.js/src/traces/scattermapbox/index.js:30:21)
      at Object.<anonymous> (../../../node_modules/plotly.js/lib/scattermapbox.js:11:18)
      at Object.<anonymous> (../../../node_modules/plotly.js/lib/index.js:52:5)
      at Object.<anonymous> (app.module.ts:251:24)
      at Object.<anonymous> (app.module.spec.ts:2:1)

```
I already tried to place the following snippets into the test suite:
```
window.URL.createObjectURL = function() {};
or
window.URL.createObjectURL = jest.fn() {};
```
Still fails if I run the tests.
Everything works fine in the frontend and I can use plotly as expected.

**Comment by andrefarzat** [comment]
Hello @jeckgit, plotly.js library is meant to be used only in browser. Unfortunately it doesn't work on node server side, thus jest isn't a good option to test it. Once you're using angular, why not use jasmine, the library used in `ng test` ?

**Comment by andrefarzat** [comment]
Please, reopen if you have further doubts

**Comment by MartinNowak** [comment]
We mocked this, seems to come from mapbox.
```ts
window.URL.createObjectURL = function () {
  return 'blob:';
};
```
via https://github.com/plotly/react-plotly.js/issues/115#issuecomment-448687417
